CUR_DIR=$(shell pwd)

test:
	echo "test array"
	cd $(CUR_DIR)/linear_list/array && make test

	echo "test list"
	cd $(CUR_DIR)/linear_list/link_list && make test

	echo "test stack"
	cd $(CUR_DIR)/stack && make test

	echo "test queue"
	cd $(CUR_DIR)/queue && make test

	echo "test search"
	cd $(CUR_DIR)/search && make test

	echo "test hash"
	cd $(CUR_DIR)/hash && make test

	echo "test success"